# Generated by Django 6.0 on 2025-12-23 01:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted')], db_index=True, default='pending', help_text='Pending, Reviewed, Accepted', max_length=50)),
                ('documents_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. School of Engineering', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('walkin', 'Walk-in'), ('referral', 'Referral'), ('other', 'Other')], help_text='Facebook, Walk-in, Referral', max_length=50)),
                ('current_status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('dropped', 'Dropped')], db_index=True, default='new', help_text='New, Qualified, Converted, Dropped', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('counselor', 'Counselor'), ('admin', 'Admin'), ('finance', 'Finance')], help_text='e.g. Counselor, Admin, Finance', max_length=50)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], help_text='Online, Physical', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('result_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass, Fail', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exam', to='core.application')),
            ],
            options={
                'verbose_name': 'Entrance Exam',
                'verbose_name_plural': 'Entrance Exams',
                'db_table': 'entrance_exams',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.lead'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('application_fee', 'Application Fee'), ('admission_fee', 'Admission Fee'), ('semester_fee', 'Semester Fee')], help_text='Application Fee, Admission Fee, Semester Fee', max_length=50)),
                ('method', models.CharField(choices=[('esewa', 'E-Sewa'), ('khalti', 'Khalti'), ('bank_voucher', 'Bank Voucher'), ('connectips', 'ConnectIPS')], help_text='E-Sewa, Khalti, Bank Voucher, ConnectIPS', max_length=50)),
                ('transaction_ref_id', models.CharField(help_text='Bank or wallet transaction ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Pending, Verified, Failed', max_length=20)),
                ('application', models.ForeignKey(help_text='Link to specific application', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.application')),
                ('lead', models.ForeignKey(help_text='Link to lead for contact info', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.lead')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('prog_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. BE Computer, B.Sc. Nursing', max_length=255)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.program'),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('schol_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('merit', 'Merit'), ('quota', 'Quota'), ('financial_aid', 'Financial Aid')], help_text='Merit, Quota, Financial Aid', max_length=50)),
                ('percentage_off', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_approved', models.BooleanField(default=False)),
                ('exam', models.OneToOneField(help_text='Linked to the entrance exam result', on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='core.entranceexam')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'db_table': 'scholarships',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Which counselor is handling this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='core.staff'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('followup_id', models.AutoField(primary_key=True, serialize=False)),
                ('followup_date', models.DateTimeField()),
                ('mode', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], help_text='Call, Email, WhatsApp', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('next_action_date', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.lead')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.staff')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'db_table': 'follow_ups',
                'ordering': ['-followup_date'],
            },
        ),
    ]
