# Generated by Django 6.0 on 2026-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='desired_intake_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gpa_or_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School (+2 / A-Level)'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('diploma_certificate', 'Diploma / Certificate')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='intake_semester',
            field=models.CharField(blank=True, choices=[('spring', 'Spring (Jan-May)'), ('fall', 'Fall (Aug-Dec)'), ('summer', 'Summer (May-Aug)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_study_mode',
            field=models.CharField(blank=True, choices=[('on_campus', 'On-Campus'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='previous_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='program_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='scholarship_interest',
            field=models.CharField(blank=True, choices=[('yes', 'Yes, interested'), ('no', 'No, self-funded'), ('unsure', 'Not sure yet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('google_search', 'Google Search'), ('referral', 'Referral'), ('education_fair', 'Education Fair'), ('walk_in', 'Walk-In'), ('advertisement', 'Advertisement'), ('website', 'Website'), ('alumni', 'Alumni'), ('facebook', 'Facebook'), ('walkin', 'Walk-in'), ('other', 'Other')], help_text='How the lead heard about the institution', max_length=50),
        ),
    ]
