# Generated by Django 5.2 on 2026-03-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_approved_at_application_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='current_status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('followup', 'Follow-up'), ('exams', 'Exams'), ('passed', 'Passed'), ('failed', 'Failed'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], db_index=True, default='new', help_text='New, Qualified, Converted, Dropped', max_length=50),
        ),
    ]
