# Generated by Django 5.2 on 2026-03-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_staff_bio_staff_department_staff_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='application',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exam_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('physical', 'Physical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='current_status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('followup', 'Follow-up'), ('exams', 'Exams'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], db_index=True, default='new', help_text='New, Qualified, Converted, Dropped', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
