# Generated by Django 6.0 on 2026-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_lead_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], help_text='e.g. Counselor, Admin, Finance', max_length=50),
        ),
    ]
