# Generated by Django 6.0 on 2026-03-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('staff', 'Staff')], help_text='e.g. Counselor, Admin, Finance', max_length=50),
        ),
    ]
