# Generated by Django 5.2 on 2026-03-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0012_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this staff member belongs to', related_name='staff_members', to='auth.group'),
        ),
    ]
