# Generated by Django 5.2 on 2026-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_admin_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='education_document',
            field=models.FileField(blank=True, null=True, upload_to='lead_documents/'),
        ),
    ]
