# Generated by Django 5.2 on 2026-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_education_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='highest_education_level',
            field=models.CharField(choices=[('high_school', 'High School (+2 / A-Level)'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('diploma_certificate', 'Diploma / Certificate')], default='high_school', max_length=30),
        ),
    ]
