# Generated by Django 5.2 on 2026-03-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_make_education_level_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='desired_intake_year',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='intake_semester',
        ),
    ]
